-   id: update-pip-licenses
    name: update the LICENSES file via pip-licenses
    description: generate a LICENSES file from all pip installed packages via pip-licenses
    entry: pip-licenses --format=plain-vertical --with-license-file --output-file=LICENSES --no-license-path
    language: python
